version: "3.9"

services:

  mysql:
    image: mysql:8
    container_name: mysql-votacao
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: votacaoPauta
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - votacao-network

  api:
    build: .
    container_name: votacao-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/votacaoPauta
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - votacao-network

volumes:
  mysql_data:

networks:
  votacao-network: