spring.application.name=votacao_pauta

server.port=8080

# Datasource
#spring.datasource.url=jdbc:mysql://localhost:3306/votacaoPauta?useSSL=false&serverTimezone=UTC
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/votacaoPauta}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
#spring.datasource.username=root
#spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Encoding
spring.datasource.hikari.connection-init-sql=SET NAMES utf8mb4

user-info.url=https://user-info.herokuapp.com

usar-associado-remoto=false

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

logging.level.org.springdoc=INFO
logging.level.org.springframework=INFO


